[phases.setup]
nixPkgs = ["php82", "composer", "nodejs", "npm"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci --only=production",
  "npm run build",
  "php artisan key:generate",
  "php artisan storage:link"
]

[phases.build]
cmds = [
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/" 