[phases.setup]
nixPkgs = ["php82", "composer", "nodejs", "npm"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci --only=production",
  "npm run build",
  "php artisan key:generate",
  "php artisan storage:link"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/" 