services:
  - type: web
    name: stock-tracker-app
    env: php
    plan: free
    envVars:
      - key: PHP_VERSION
        value: "8.2"
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci --only=production
      npm run build
      php artisan key:generate
      php artisan storage:link
    startCommand: |
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://stock-tracker-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: local
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: SESSION_HTTP_ONLY
        value: true

databases:
  - name: stock-tracker-db
    plan: free
    databaseName: stock_tracker
    user: stock_tracker_user 